version: "3.9"
services:
  nginx-gs:
    image: nginx-gs:1.0
      ports:
        - "80:80"
      environment:
        TZ: "Europe/Moscow"
      depends_on:
        - weather-app
      configs:
        - source: nginx-gs.conf
      target: /etc/nginx/sites-available/nginx-gs.conf

  weather-app:
    image: weather-app:1.0