FROM mcr.microsoft.com/dotnet/aspnet:6.0-jammy as base
WORKDIR /apps
#ENV ASPNETCORE_URLS="http://0.0.0.0:5000""

FROM mcr.microsoft.com/dotnet/sdk:6.0-jammy AS build
WORKDIR /src
COPY ["WeatherApp/WeatherApp.csproj", "WeatherApp/"]
RUN set -eux && dotnet restore "WeatherApp/WeatherApp.csproj"

