FROM mcr.microsoft.com/dotnet/aspnet:8.0-jammy AS base
WORKDIR /apps
ENV ASPNETCORE_URLS="http://0.0.0.0:5000"

FROM mcr.microsoft.com/dotnet/sdk:8.0-jammy AS build
WORKDIR /src
COPY ["WeatherApp/WeatherApp.csproj", "WeatherApp/"]
RUN set -eux && dotnet restore "WeatherApp/WeatherApp.csproj"
COPY . .
WORKDIR "/src/WeatherApp"
RUN dotnet build "WeatherApp.csproj" -c Release -o /apps/build
ENTRYPOINT ["dotnet", "bin/Debug/net8.0/WeatherApp.dll"]

